# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
    body_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: [html, json, xml ], fallback_format: html, prefer_extension: true }
    param_fetcher_listener: true
    view:
        view_response_listener: true
        templating_formats:
#            json: false
            html: true
        formats:
            json: true
            html: true

    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_converter:
        enabled: true
    exception:
      enabled: true
      messages:
          Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
          \Exception: true
      exception_controller: 'fos_rest.exception.controller:showAction'