# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    routing_loader:
        default_format: json
        include_format: false
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        templating_formats:
            json: false
        formats:
            json: true
    exception:
      enabled: true
      messages:
          Symfony\Component\HttpKernel\Exception\BadRequestHttpException: true
          \Exception: true
      exception_controller: 'fos_rest.exception.controller:showAction'